### ISSUE TITLE
Odometry velocity too large

### ISSUE THREAD

**Issue by Zy75** [AutonomyLab/libcreate#36]
Hi,

I am using Create 2 and plannning to use gmapping and move_base. I found that odometry velocities ( Twist ) of both x and theta are too large.
When I control the robot with a gamepad, x velocity is over 2.0 but in real measurement it is less than 0.5( m/s). Theta velocity is over 15.0 but really much less.

Is it only me experiencing this?

I added print statements in the libcreate source code and looked for what was happening.

And I found that usually the odometry data come every 0.003s ( into onData func in create.cpp ) ,but sometimes interval is as long as 0.08s.  The long interval(0.08s) is more than 20 times as long as the short interval (0.003s).

My guess of the problem is because velocity is distance divided by time, the velocity computed during the short interval is large, and this large velocity is kept alive during the long period, so this causes large velocity in time average. 

After I have changed the source code so that it computes velocity after averaging for 0.4s,
The problem has been solved, and as a result, my robot project is now working!

**Comment by jacobperron** [comment]
@Zy75 Thanks for reporting this. I'll take a closer look with my robots when I get a chance and see if I run into similar issues.

**Comment by Zy75** [comment]
@jacobperron Thanks for reading the post. The following is additional information.

I use Raspberry Pi 3(RPi3) to connect to Create 2.  RPi3 is mounted on the robot. 
RPi3 is running OS Raspbian. ( I installed ROS from source. )
I installed create_autonomy and libcreate.
RPi3 and Create 2 are connected with the USB-serial cable included in the box.
To confirm the problem, run [$ rostopic echo /odom ] and see Twist message. 

My SLAM+Navigation is working now, So I'm not in a hurry. Thanks in advance.

**Comment by tim-fan** [comment]
Just to note I'm seeing the same issue.

I'm using a create 2 and a raspberry pi 4 with ubuntu focal, with create_autonomy running in a bionic docker container. 

I was observing odometry velocities of up to 10 m/s. My move_base is behaving erratically and I suspect this is the cause.

**Comment by jacobperron** [comment]
The velocity being computed here is over a very short time window (as @Zy75 points out):

https://github.com/AutonomyLab/libcreate/blob/cc95ad35a01835cbc3ead0aef0a09b6c88272626/src/create.cpp#L187-L189

I suspect this leads to very noisy values, though I haven't had a chance to inspect them myself yet. @tim-fan Are you seeing spikes of 10m/s velocities or consistently high velocities? Computing velocity over a larger time window should help in either case.

**Comment by jacobperron** [comment]
With the ROS driver, it might be interesting to see what velocities look like after increasing the value of the [`loop_hz_` parameter](https://github.com/AutonomyLab/create_robot/blob/melodic/create_driver/src/create_driver.cpp#L47) to match the underlying update rate `libcreate`, e.g. a value of 300Hz.

**Comment by tim-fan** [comment]
> Are you seeing spikes of 10m/s velocities or consistently high velocities?

Here's a velocity plot over a roughly 45 second window, while driving at a steady velocity (somewhere between 0.5 and 1 m/s, I'd guess):
![odom_vel](https://user-images.githubusercontent.com/7835911/104864932-6428ce00-599f-11eb-8722-8fccd526ea03.png)

This is showing the odom field twist.twist.linear.x plotted by time. I'm receiving odom at 10Hz.

So the high velocities are fairly consistent. There's the occasional drop to near zero in roughly 1 out of each 100 samples.

**Comment by jacobperron** [comment]
Interesting, there's clearly a systematic error. The math for computing distance traveled looks correct to me (and I'm pretty sure I've seen reasonable values in the past): 

https://github.com/AutonomyLab/libcreate/blob/cc95ad35a01835cbc3ead0aef0a09b6c88272626/src/create.cpp#L159-L164

One potential source of error is if the system clock isn't stable. Really, I think we should use a steady clock for computing the delta-time. Here's a change to use a steady clock, though I don't expect that to resolve the large velocity issue:

https://github.com/AutonomyLab/libcreate/pull/59

**Comment by tim-fan** [comment]
Hello, I've looked into this a bit more by printing `dt` values.

Basically I saw the same thing @Zy75  mentioned, with a series of very small `dt` values, followed by a large one up to 0.1s. During the large `dt` window the `vel` value is kept from the previous calculation, which used a small `dt` and hence over estimates velocity. Note for any velocity query there is a small chance that the previous calculation was based on the large `dt` value, I think this explains the intermittent drops to near zero velocity in the graph I posted previously.

My guess atm is that this is not an issue with the system clock, but more related to the timing with which encoder values are received over the serial connection. I'm guessing the encoder values are put into some sort of queue and then sent all at once, such that the `dt` between receiving the encoder values does not accurately reflect the `dt` with which the values were actually captured.

Anyway, the fix I tried was to follow @Zy75 and compute velocity over a window. I used 0.15s for the window size. This just needs to be large enough to cover the largest `dt` value between updates. After applying the change my velocity values look realistic.

I've put my change in [a fork](https://github.com/tim-fan/libcreate/commit/b8b03097bf8cdc10afe3980a01e2613c713e0703). If you are OK with this approach to fixing the issue I can submit a pull request.

**Comment by jacobperron** [comment]
@tim-fan Your changes look like a reasonable addition. Two things I would modify:

1. Make the time window configurable (via a setter method).
2. Rename the `motion_history_length` variable to match the style of the rest of the code and perhaps call it `velocityTimeWindow`.

I'm happy to accept a PR :slightly_smiling_face:

**Comment by tim-fan** [comment]
Hello, I have an update on this;

I ran some more tests on my change of calculating velocity over a larger time window, and was dissatisfied with the results, as it seems like the window needs to be very large to get rid of all the noise. 
To illustrate, here's the output velocity when calculated over a 300ms window:
![odom_x_300ms_average](https://user-images.githubusercontent.com/7835911/108784654-bf6c6280-75d4-11eb-96c7-ea69d9705cb0.png)
That profile is still showing velocity over-estimation with occasional downward spikes, although the situation is improved from when no averaging is used.
Trying a larger window (500ms) to reduce noise ever further:
![odom_x_500ms_average](https://user-images.githubusercontent.com/7835911/108784893-36096000-75d5-11eb-8224-2f8f6707299b.png)
However the noise is still present, and I wouldn't be happy to introduce that much delay into the velocity calculation.

Changing course, I considered the possibility the assumption that the encoder samples are being taken in the create firmware with a fixed `dt`, and if I could determine that fixed value then I could use that for velocity calculation, without having to average over the encoder data. 

So I made a branch where an average `dt` is used based on the last 100 `dt` values from subsequent `onData` calls. Then I used this average `dt` in the velocity calculations. This gave the following velocity profile:
![odom_x_dt_average_100_samples](https://user-images.githubusercontent.com/7835911/108785433-44a44700-75d6-11eb-93f0-a4d5d78f1d09.png)

I'm happy with those results as noise is reduced without introducing averaging delay into the velocity output. So that's the change I'll propose in a pull request.
